### ISSUE TITLE
Syntax error for node v6.10.2

### ISSUE THREAD

**Issue by akoppela** [zwilias/elm-xref#1]
There is a syntax error for `...` in node v6.10.2. Any plan to support older versions?

```
elm-xref
/Users/akoppela/.nvm/versions/node/v6.10.2/lib/node_modules/elm-xref/index.js:227
                return { ...pkg, version: versions[0] };
                         ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
```

**Comment by akoppela** [comment]
PR: https://github.com/zwilias/elm-xref/pull/2

**Comment by zwilias** [comment]
Part of 0.2.1. Thanks for the contribution!
